### ISSUE TITLE
Can i reverse engineer?

### ISSUE THREAD

**Issue by nnikospapadakis** [Rootthecause/HVI#2]
Hello im from a formula student team and i want to open your design through altium designer, is there a way you can provide me the PcbDoc files? I want to add some components for our specific use. I really appreciate it. THANK YOU!!

**Comment by Rootthecause** [comment]
Hi!
As far as I know, there is an import function in altium for KiKAD files. As I do not have Altium, I cannot provide altium files. 
Otherwise I would recommend an open source and free for everyone designer like KiCAD ;)
